theme:
  scheme: light dark
  navbar:
    link: /
    logo: "/assets/favicon/favicon.svg"
    brand: "tecsmith.design"
    container: 1 # 1 = nav > div:.container; 2 = div:.container > nav; 0 = nav
    class: "navbar-dark navbar-brand-3 bg-primary bg-brand-3"
  main:
    class: container my-4
  footer:
    class: bg-footer my-3 pt-3
    copyright: 2024
    brand: "tecsmith.design"
  features:
    detect_os: 0       # 0 (default) = no, 1 = yes
    external_links: 0  # 0 (default) = off, 1 = make target _blank, 2 = add icon, 3 = both
    to_top_btn: 1      # 0 (default) = off, 1 = on
    tool_tips: 0       # 0 (default) = off, 1 = on
  color: #c50
css:
  # Find latest from https://cdnjs.com/
  # Generate SRI Hash from https://www.srihash.org/
  bootstrap:
    # Bootlace 5.3.7
    url: "https://cdn.jsdelivr.net/gh/silvinor/bootlace@5.3.7/dist/css/bootlace.min.css"
    hash: "sha384-eot1opfzGFlwUV+MPPLx3Bn3q/s3cWjnH2wWSurFX36RR6y5XbAuJ1d9gbQUiYKG"
  fontawesome:
    # FontAwesome 7.0.0
    url: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
    hash: "sha384-tGBVFh2h9Zcme3k9gJLbGqDpD+jRd419j/6N32rharcTZa1X6xgxug6pFMGonjxU"
js:
  popper:
    # Popper JS 2.11.8
    url: "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    hash: "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  bootstrap:
    # Bootstrap JS 5.3.7
    url: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js"
    hash: "sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK"
